version: '3'

services: 
  app:
    build: ./app
    depends_on: 
      - db
  db:
    image: mysql:8
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - app

